export enum CustodyEventType {
  EVIDENCE_REGISTERED = 'EVIDENCE_REGISTERED',
  FILE_UPLOADED = 'FILE_UPLOADED',
  ACCESSED = 'ACCESSED',
  TRANSFERRED = 'TRANSFERRED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  INTEGRITY_VERIFIED = 'INTEGRITY_VERIFIED',
  NOTE_ADDED = 'NOTE_ADDED',
  RELEASED = 'RELEASED',
  ARCHIVED = 'ARCHIVED',
  TRANSFER_REQUESTED = 'TRANSFER_REQUESTED',
  TRANSFER_APPROVED = 'TRANSFER_APPROVED',
  TRANSFER_REJECTED = 'TRANSFER_REJECTED',
}
