export enum EvidenceStatus {
  REGISTERED = 'REGISTERED',
  IN_STORAGE = 'IN_STORAGE',
  IN_EXAMINATION = 'IN_EXAMINATION',
  TRANSFER_PENDING = 'TRANSFER_PENDING',
  TRANSFERRED = 'TRANSFERRED',
  INTEGRITY_WARNING = 'INTEGRITY_WARNING',
  ARCHIVED = 'ARCHIVED',
}
