export enum EvidenceType {
  COMPUTER = 'COMPUTER',
  MOBILE_DEVICE = 'MOBILE_DEVICE',
  STORAGE_DEVICE = 'STORAGE_DEVICE',
  DOCUMENT = 'DOCUMENT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  LOG_FILE = 'LOG_FILE',
  NETWORK_CAPTURE = 'NETWORK_CAPTURE',
  EMAIL = 'EMAIL',
  OTHER = 'OTHER',
}
